service: backend
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

functions:
  createAccount:
    handler: src/modules/user/controller.createAccount
    events:
    - http:
        path: user/create
        method: post